<a href="https://colab.research.google.com/github/sazedAawal/MachineLearningProjects/blob/main/LoanCheck_CatBoost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp313-cp313-manylinux2014_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.13/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.1.3)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.2.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.13/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp313-cp313-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.3 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import statsmodels.api as sm
from catboost import CatBoostClassifier
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, accuracy_score

In [3]:
data = pd.read_csv('/content/sample_data/data.csv')

In [4]:
data

     ApplicantIncome  CoapplicantIncome  ...  Credit_History  Loan_Status
0             5849.0                0.0  ...             Yes            1
1             4583.0             1508.0  ...             Yes            0
2             3000.0                0.0  ...             Yes            1
3             2583.0             2358.0  ...             Yes            1
4             6000.0                0.0  ...             Yes            1
..               ...                ...  ...             ...          ...
609           2900.0                0.0  ...             Yes            1
610           4106.0                0.0  ...             Yes            1
611           8072.0              240.0  ...             Yes            1
612           7583.0                0.0  ...             Yes            1
613           4583.0                0.0  ...              No            0

[614 rows x 6 columns]

In [12]:
df = data

In [32]:
def resumetable(df):
  print(f"Dataset Shape: {df.shape}")
  summary = pd.DataFrame(df.dtypes, columns=['dtypes'])
  summary = summary.reset_index()

  summary['Name'] = summary['index']
  summary = summary[['Name', 'dtypes']]
  summary['Missing'] = df.isnull().sum().values
  summary['Uniques'] = df.nunique().values

  summary['First Value'] = df.loc[0].values
  summary['Second Value'] = df.loc[1].values
  return summary

In [24]:
df.head()

   ApplicantIncome  CoapplicantIncome  ...  Credit_History  Loan_Status
0           5849.0                0.0  ...             Yes            1
1           4583.0             1508.0  ...             Yes            0
2           3000.0                0.0  ...             Yes            1
3           2583.0             2358.0  ...             Yes            1
4           6000.0                0.0  ...             Yes            1

[5 rows x 6 columns]

In [25]:
print('Total number of rows in dataset = {}'.format(df.shape[0]))
print('Total number of columns in dataset = {}'.format(df.shape[1]))

Total number of rows in dataset = 614
Total number of columns in dataset = 6

In [33]:
result = resumetable(df)
result

Dataset Shape: (614, 6)

                Name   dtypes  Missing  Uniques First Value Second Value
0    ApplicantIncome  float64        2      503      5849.0       4583.0
1  CoapplicantIncome  float64        2      287         0.0       1508.0
2         LoanAmount  float64        3      203         0.0        128.0
3   Loan_Amount_Term  float64        2       11       360.0        360.0
4     Credit_History   object        0        2         Yes          Yes
5        Loan_Status    int64        0        2           1            0

In [35]:
target_col = 'Loan_Status'
x = df.loc[:,df.columns != target_col]
y = df.loc[:, target_col]

In [36]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.33, random_state=42)

In [37]:
x_train.head()

     ApplicantIncome  CoapplicantIncome  ...  Loan_Amount_Term  Credit_History
244           3406.0             4417.0  ...             360.0             Yes
393           1993.0             1625.0  ...             180.0             Yes
310           2917.0                0.0  ...             360.0             Yes
408           8300.0                0.0  ...             300.0              No
572          16666.0                0.0  ...             360.0             Yes

[5 rows x 5 columns]

In [38]:
features = list(x_train.columns)

In [39]:
cat_features = ['Credit_History']

In [45]:
model_cb = CatBoostClassifier(task_type='GPU',
                              iterations=100,
                              random_state=2026,
                              eval_metric='F1')

In [46]:
model_cb.fit(x_train, y_train, cat_features=cat_features, plot=True,
             eval_set=(x_test, y_test))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Learning rate set to 0.199227
0:	learn: 0.8590164	test: 0.8226950	best: 0.8226950 (0)	total: 21.5ms	remaining: 2.13s
1:	learn: 0.8580645	test: 0.8339223	best: 0.8339223 (1)	total: 39.1ms	remaining: 1.92s
2:	learn: 0.8529887	test: 0.8339223	best: 0.8339223 (1)	total: 54.1ms	remaining: 1.75s
3:	learn: 0.8534622	test: 0.8339223	best: 0.8339223 (1)	total: 78.8ms	remaining: 1.89s
4:	learn: 0.8520900	test: 0.8339223	best: 0.8339223 (1)	total: 170ms	remaining: 3.22s
5:	learn: 0.8539326	test: 0.8339223	best: 0.8339223 (1)	total: 191ms	remaining: 3s
6:	learn: 0.8520900	test: 0.8309859	best: 0.8339223 (1)	total: 212ms	remaining: 2.81s
7:	learn: 0.8539326	test: 0.8251748	best: 0.8339223 (1)	total: 236ms	remaining: 2.71s
8:	learn: 0.8544000	test: 0.8251748	best: 0.8339223 (1)	total: 254ms	remaining: 2.57s
9:	learn: 0.8507223	test: 0.8292683	best: 0.8339223 (1)	total: 272ms	remaining: 2.45s
10:	learn: 0.8520900	test: 0.8251748	best: 0.8339223 (1)	total: 294ms	remaining: 2.38s
11:	learn: 0.8539326	test: 0.8251748	best: 0.8339223 (1)	total: 312ms	remaining: 2.29s
12:	learn: 0.8553055	test: 0.8251748	best: 0.8339223 (1)	total: 332ms	remaining: 2.22s
13:	learn: 0.8571429	test: 0.8321678	best: 0.8339223 (1)	total: 352ms	remaining: 2.16s
14:	learn: 0.8608000	test: 0.8362369	best: 0.8362369 (14)	total: 377ms	remaining: 2.14s
15:	learn: 0.8594249	test: 0.8362369	best: 0.8362369 (14)	total: 397ms	remaining: 2.09s
16:	learn: 0.8589744	test: 0.8321678	best: 0.8362369 (14)	total: 416ms	remaining: 2.03s
17:	learn: 0.8585209	test: 0.8304498	best: 0.8362369 (14)	total: 437ms	remaining: 1.99s
18:	learn: 0.8621795	test: 0.8292683	best: 0.8362369 (14)	total: 457ms	remaining: 1.95s
19:	learn: 0.8672000	test: 0.8263889	best: 0.8362369 (14)	total: 477ms	remaining: 1.91s
20:	learn: 0.8666667	test: 0.8206897	best: 0.8362369 (14)	total: 495ms	remaining: 1.86s
21:	learn: 0.8648649	test: 0.8219178	best: 0.8362369 (14)	total: 522ms	remaining: 1.85s
22:	learn: 0.8684628	test: 0.8137931	best: 0.8362369 (14)	total: 541ms	remaining: 1.81s
23:	learn: 0.8684628	test: 0.8137931	best: 0.8362369 (14)	total: 555ms	remaining: 1.76s
24:	learn: 0.8648649	test: 0.8137931	best: 0.8362369 (14)	total: 559ms	remaining: 1.68s
25:	learn: 0.8702532	test: 0.8137931	best: 0.8362369 (14)	total: 563ms	remaining: 1.6s
26:	learn: 0.8720379	test: 0.8166090	best: 0.8362369 (14)	total: 567ms	remaining: 1.53s
27:	learn: 0.8702532	test: 0.8166090	best: 0.8362369 (14)	total: 570ms	remaining: 1.47s
28:	learn: 0.8720379	test: 0.8166090	best: 0.8362369 (14)	total: 574ms	remaining: 1.4s
29:	learn: 0.8702532	test: 0.8166090	best: 0.8362369 (14)	total: 577ms	remaining: 1.35s
30:	learn: 0.8680445	test: 0.8166090	best: 0.8362369 (14)	total: 581ms	remaining: 1.29s
31:	learn: 0.8698413	test: 0.8206897	best: 0.8362369 (14)	total: 584ms	remaining: 1.24s
32:	learn: 0.8716323	test: 0.8206897	best: 0.8362369 (14)	total: 588ms	remaining: 1.19s
33:	learn: 0.8765823	test: 0.8206897	best: 0.8362369 (14)	total: 591ms	remaining: 1.15s
34:	learn: 0.8769716	test: 0.8235294	best: 0.8362369 (14)	total: 595ms	remaining: 1.1s
35:	learn: 0.8805031	test: 0.8235294	best: 0.8362369 (14)	total: 601ms	remaining: 1.07s
36:	learn: 0.8818898	test: 0.8235294	best: 0.8362369 (14)	total: 605ms	remaining: 1.03s
37:	learn: 0.8805031	test: 0.8275862	best: 0.8362369 (14)	total: 608ms	remaining: 993ms
38:	learn: 0.8818898	test: 0.8275862	best: 0.8362369 (14)	total: 612ms	remaining: 957ms
39:	learn: 0.8836478	test: 0.8275862	best: 0.8362369 (14)	total: 616ms	remaining: 923ms
40:	learn: 0.8836478	test: 0.8304498	best: 0.8362369 (14)	total: 619ms	remaining: 891ms
41:	learn: 0.8836478	test: 0.8263889	best: 0.8362369 (14)	total: 623ms	remaining: 860ms
42:	learn: 0.8854003	test: 0.8263889	best: 0.8362369 (14)	total: 626ms	remaining: 830ms
43:	learn: 0.8867925	test: 0.8263889	best: 0.8362369 (14)	total: 630ms	remaining: 801ms
44:	learn: 0.8867925	test: 0.8263889	best: 0.8362369 (14)	total: 633ms	remaining: 774ms
45:	learn: 0.8867925	test: 0.8304498	best: 0.8362369 (14)	total: 637ms	remaining: 748ms
46:	learn: 0.8881890	test: 0.8222997	best: 0.8362369 (14)	total: 640ms	remaining: 722ms
47:	learn: 0.8860759	test: 0.8344828	best: 0.8362369 (14)	total: 644ms	remaining: 698ms
48:	learn: 0.8913386	test: 0.8344828	best: 0.8362369 (14)	total: 648ms	remaining: 674ms
49:	learn: 0.8881890	test: 0.8316151	best: 0.8362369 (14)	total: 651ms	remaining: 651ms
50:	learn: 0.8899371	test: 0.8344828	best: 0.8362369 (14)	total: 655ms	remaining: 629ms
51:	learn: 0.8913386	test: 0.8344828	best: 0.8362369 (14)	total: 659ms	remaining: 608ms
52:	learn: 0.8881890	test: 0.8316151	best: 0.8362369 (14)	total: 662ms	remaining: 587ms
53:	learn: 0.8874802	test: 0.8344828	best: 0.8362369 (14)	total: 666ms	remaining: 567ms
54:	learn: 0.8874802	test: 0.8316151	best: 0.8362369 (14)	total: 669ms	remaining: 547ms
55:	learn: 0.8906498	test: 0.8316151	best: 0.8362369 (14)	total: 673ms	remaining: 529ms
56:	learn: 0.8920635	test: 0.8287671	best: 0.8362369 (14)	total: 676ms	remaining: 510ms
57:	learn: 0.8920635	test: 0.8287671	best: 0.8362369 (14)	total: 680ms	remaining: 492ms
58:	learn: 0.8920635	test: 0.8287671	best: 0.8362369 (14)	total: 683ms	remaining: 475ms
59:	learn: 0.8906498	test: 0.8344828	best: 0.8362369 (14)	total: 687ms	remaining: 458ms
60:	learn: 0.8924051	test: 0.8344828	best: 0.8362369 (14)	total: 691ms	remaining: 441ms
61:	learn: 0.8952381	test: 0.8344828	best: 0.8362369 (14)	total: 694ms	remaining: 425ms
62:	learn: 0.8998410	test: 0.8344828	best: 0.8362369 (14)	total: 698ms	remaining: 410ms
63:	learn: 0.8998410	test: 0.8344828	best: 0.8362369 (14)	total: 701ms	remaining: 395ms
64:	learn: 0.8998410	test: 0.8344828	best: 0.8362369 (14)	total: 705ms	remaining: 380ms
65:	learn: 0.8998410	test: 0.8344828	best: 0.8362369 (14)	total: 709ms	remaining: 365ms
66:	learn: 0.8998410	test: 0.8344828	best: 0.8362369 (14)	total: 712ms	remaining: 351ms
67:	learn: 0.8998410	test: 0.8344828	best: 0.8362369 (14)	total: 716ms	remaining: 337ms
68:	learn: 0.9027113	test: 0.8344828	best: 0.8362369 (14)	total: 719ms	remaining: 323ms
69:	learn: 0.8998410	test: 0.8344828	best: 0.8362369 (14)	total: 728ms	remaining: 312ms
70:	learn: 0.9027113	test: 0.8344828	best: 0.8362369 (14)	total: 736ms	remaining: 300ms
71:	learn: 0.9027113	test: 0.8344828	best: 0.8362369 (14)	total: 739ms	remaining: 288ms
72:	learn: 0.9041534	test: 0.8333333	best: 0.8362369 (14)	total: 750ms	remaining: 277ms
73:	learn: 0.9093800	test: 0.8344828	best: 0.8362369 (14)	total: 759ms	remaining: 267ms
74:	learn: 0.9059011	test: 0.8344828	best: 0.8362369 (14)	total: 766ms	remaining: 255ms
75:	learn: 0.9059011	test: 0.8344828	best: 0.8362369 (14)	total: 771ms	remaining: 243ms
76:	learn: 0.9073482	test: 0.8333333	best: 0.8362369 (14)	total: 774ms	remaining: 231ms
77:	learn: 0.9073482	test: 0.8304498	best: 0.8362369 (14)	total: 778ms	remaining: 219ms
78:	learn: 0.9105431	test: 0.8292683	best: 0.8362369 (14)	total: 781ms	remaining: 208ms
79:	learn: 0.9105431	test: 0.8251748	best: 0.8362369 (14)	total: 785ms	remaining: 196ms
80:	learn: 0.9090909	test: 0.8292683	best: 0.8362369 (14)	total: 788ms	remaining: 185ms
81:	learn: 0.9088000	test: 0.8210526	best: 0.8362369 (14)	total: 792ms	remaining: 174ms
82:	learn: 0.9102564	test: 0.8292683	best: 0.8362369 (14)	total: 796ms	remaining: 163ms
83:	learn: 0.9134615	test: 0.8292683	best: 0.8362369 (14)	total: 801ms	remaining: 153ms
84:	learn: 0.9137380	test: 0.8210526	best: 0.8362369 (14)	total: 806ms	remaining: 142ms
85:	learn: 0.9134615	test: 0.8210526	best: 0.8362369 (14)	total: 810ms	remaining: 132ms
86:	learn: 0.9166667	test: 0.8210526	best: 0.8362369 (14)	total: 813ms	remaining: 122ms
87:	learn: 0.9152000	test: 0.8251748	best: 0.8362369 (14)	total: 817ms	remaining: 111ms
88:	learn: 0.9184000	test: 0.8251748	best: 0.8362369 (14)	total: 820ms	remaining: 101ms
89:	learn: 0.9166667	test: 0.8251748	best: 0.8362369 (14)	total: 824ms	remaining: 91.6ms
90:	learn: 0.9184000	test: 0.8222997	best: 0.8362369 (14)	total: 828ms	remaining: 81.9ms
91:	learn: 0.9216000	test: 0.8222997	best: 0.8362369 (14)	total: 831ms	remaining: 72.3ms
92:	learn: 0.9181380	test: 0.8251748	best: 0.8362369 (14)	total: 835ms	remaining: 62.8ms
93:	learn: 0.9198718	test: 0.8280702	best: 0.8362369 (14)	total: 838ms	remaining: 53.5ms
94:	learn: 0.9198718	test: 0.8280702	best: 0.8362369 (14)	total: 842ms	remaining: 44.3ms
95:	learn: 0.9230769	test: 0.8280702	best: 0.8362369 (14)	total: 846ms	remaining: 35.2ms
96:	learn: 0.9213483	test: 0.8280702	best: 0.8362369 (14)	total: 849ms	remaining: 26.3ms
97:	learn: 0.9228296	test: 0.8251748	best: 0.8362369 (14)	total: 852ms	remaining: 17.4ms
98:	learn: 0.9228296	test: 0.8251748	best: 0.8362369 (14)	total: 856ms	remaining: 8.64ms
99:	learn: 0.9228296	test: 0.8251748	best: 0.8362369 (14)	total: 859ms	remaining: 0us
bestTest = 0.8362369338
bestIteration = 14
Shrink model to first 15 iterations.

CatBoostClassifier(eval_metric='F1', iterations=100, random_state=2026, task_type='GPU')

In [47]:
y_pred = model_cb.predict(x_test)

In [48]:
f1_score(y_test, y_pred)

0.8362369337979094

In [49]:
accuracy_score(y_test, y_pred)

0.7684729064039408